export interface CountryCode {
  commonName: string;
  dialString: string;
  flagIcon: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { commonName: 'United States / Canada', dialString: '+1', flagIcon: '🇺🇸' },
  { commonName: 'Russia / Kazakhstan', dialString: '+7', flagIcon: '🇷🇺' },
  { commonName: 'Egypt', dialString: '+20', flagIcon: '🇪🇬' },
  { commonName: 'South Africa', dialString: '+27', flagIcon: '🇿🇦' },
  { commonName: 'Greece', dialString: '+30', flagIcon: '🇬🇷' },
  { commonName: 'Netherlands', dialString: '+31', flagIcon: '🇳🇱' },
  { commonName: 'Belgium', dialString: '+32', flagIcon: '🇧🇪' },
  { commonName: 'France', dialString: '+33', flagIcon: '🇫🇷' },
  { commonName: 'Spain', dialString: '+34', flagIcon: '🇪🇸' },
  { commonName: 'Hungary', dialString: '+36', flagIcon: '🇭🇺' },
  { commonName: 'Italy', dialString: '+39', flagIcon: '🇮🇹' },
  { commonName: 'Romania', dialString: '+40', flagIcon: '🇷🇴' },
  { commonName: 'Switzerland', dialString: '+41', flagIcon: '🇨🇭' },
  { commonName: 'United Kingdom', dialString: '+44', flagIcon: '🇬🇧' },
  { commonName: 'Denmark', dialString: '+45', flagIcon: '🇩🇰' },
  { commonName: 'Sweden', dialString: '+46', flagIcon: '🇸🇪' },
  { commonName: 'Norway', dialString: '+47', flagIcon: '🇳🇴' },
  { commonName: 'Poland', dialString: '+48', flagIcon: '🇵🇱' },
  { commonName: 'Germany', dialString: '+49', flagIcon: '🇩🇪' },
  { commonName: 'Peru', dialString: '+51', flagIcon: '🇵🇪' },
  { commonName: 'Mexico', dialString: '+52', flagIcon: '🇲🇽' },
  { commonName: 'Cuba', dialString: '+53', flagIcon: '🇨🇺' },
  { commonName: 'Argentina', dialString: '+54', flagIcon: '🇦🇷' },
  { commonName: 'Brazil', dialString: '+55', flagIcon: '🇧🇷' },
  { commonName: 'Chile', dialString: '+56', flagIcon: '🇨🇱' },
  { commonName: 'Colombia', dialString: '+57', flagIcon: '🇨🇴' },
  { commonName: 'Venezuela', dialString: '+58', flagIcon: '🇻🇪' },
  { commonName: 'Malaysia', dialString: '+60', flagIcon: '🇲🇾' },
  { commonName: 'Australia', dialString: '+61', flagIcon: '🇦🇺' },
  { commonName: 'Indonesia', dialString: '+62', flagIcon: '🇮🇩' },
  { commonName: 'Philippines', dialString: '+63', flagIcon: '🇵🇭' },
  { commonName: 'New Zealand', dialString: '+64', flagIcon: '🇳🇿' },
  { commonName: 'Singapore', dialString: '+65', flagIcon: '🇸🇬' },
  { commonName: 'Thailand', dialString: '+66', flagIcon: '🇹🇭' },
  { commonName: 'Japan', dialString: '+81', flagIcon: '🇯🇵' },
  { commonName: 'South Korea', dialString: '+82', flagIcon: '🇰🇷' },
  { commonName: 'Vietnam', dialString: '+84', flagIcon: '🇻🇳' },
  { commonName: 'China', dialString: '+86', flagIcon: '🇨🇳' },
  { commonName: 'Turkey', dialString: '+90', flagIcon: '🇹🇷' },
  { commonName: 'India', dialString: '+91', flagIcon: '🇮🇳' },
  { commonName: 'Pakistan', dialString: '+92', flagIcon: '🇵🇰' },
  { commonName: 'Afghanistan', dialString: '+93', flagIcon: '🇦🇫' },
  { commonName: 'Sri Lanka', dialString: '+94', flagIcon: '🇱🇰' },
  { commonName: 'Myanmar', dialString: '+95', flagIcon: '🇲🇲' },
  { commonName: 'Iran', dialString: '+98', flagIcon: '🇮🇷' },
  { commonName: 'Morocco', dialString: '+212', flagIcon: '🇲🇦' },
  { commonName: 'Algeria', dialString: '+213', flagIcon: '🇩🇿' },
  { commonName: 'Tunisia', dialString: '+216', flagIcon: '🇹🇳' },
  { commonName: 'Libya', dialString: '+218', flagIcon: '🇱🇾' },
  { commonName: 'Gambia', dialString: '+220', flagIcon: '🇬🇲' },
  { commonName: 'Senegal', dialString: '+221', flagIcon: '🇸🇳' },
  { commonName: 'Mauritania', dialString: '+222', flagIcon: '🇲🇷' },
  { commonName: 'Mali', dialString: '+223', flagIcon: '🇲🇱' },
  { commonName: 'Guinea', dialString: '+224', flagIcon: '🇬🇳' },
  { commonName: 'Ivory Coast', dialString: '+225', flagIcon: '🇨🇮' },
  { commonName: 'Burkina Faso', dialString: '+226', flagIcon: '🇧🇫' },
  { commonName: 'Niger', dialString: '+227', flagIcon: '🇳🇪' },
  { commonName: 'Togo', dialString: '+228', flagIcon: '🇹🇬' },
  { commonName: 'Benin', dialString: '+229', flagIcon: '🇧🇯' },
  { commonName: 'Mauritius', dialString: '+230', flagIcon: '🇲🇺' },
  { commonName: 'Liberia', dialString: '+231', flagIcon: '🇱🇷' },
  { commonName: 'Sierra Leone', dialString: '+232', flagIcon: '🇸🇱' },
  { commonName: 'Ghana', dialString: '+233', flagIcon: '🇬🇭' },
  { commonName: 'Nigeria', dialString: '+234', flagIcon: '🇳🇬' },
  { commonName: 'Chad', dialString: '+235', flagIcon: '🇹🇩' },
  { commonName: 'Central African Republic', dialString: '+236', flagIcon: '🇨🇫' },
  { commonName: 'Cameroon', dialString: '+237', flagIcon: '🇨🇲' },
  { commonName: 'Cape Verde', dialString: '+238', flagIcon: '🇨🇻' },
  { commonName: 'Equatorial Guinea', dialString: '+240', flagIcon: '🇬🇶' },
  { commonName: 'Gabon', dialString: '+241', flagIcon: '🇬🇦' },
  { commonName: 'Congo', dialString: '+242', flagIcon: '🇨🇬' },
  { commonName: 'DR Congo', dialString: '+243', flagIcon: '🇨🇩' },
  { commonName: 'Angola', dialString: '+244', flagIcon: '🇦🇴' },
  { commonName: 'Ethiopia', dialString: '+251', flagIcon: '🇪🇹' },
  { commonName: 'Somalia', dialString: '+252', flagIcon: '🇸🇴' },
  { commonName: 'Djibouti', dialString: '+253', flagIcon: '🇩🇯' },
  { commonName: 'Kenya', dialString: '+254', flagIcon: '🇰🇪' },
  { commonName: 'Tanzania', dialString: '+255', flagIcon: '🇹🇿' },
  { commonName: 'Uganda', dialString: '+256', flagIcon: '🇺🇬' },
  { commonName: 'Mozambique', dialString: '+258', flagIcon: '🇲🇿' },
  { commonName: 'Zambia', dialString: '+260', flagIcon: '🇿🇲' },
  { commonName: 'Madagascar', dialString: '+261', flagIcon: '🇲🇬' },
  { commonName: 'Zimbabwe', dialString: '+263', flagIcon: '🇿🇼' },
  { commonName: 'Namibia', dialString: '+264', flagIcon: '🇳🇦' },
  { commonName: 'Malawi', dialString: '+265', flagIcon: '🇲🇼' },
  { commonName: 'Botswana', dialString: '+267', flagIcon: '🇧🇼' },
  { commonName: 'Swaziland', dialString: '+268', flagIcon: '🇸🇿' },
  { commonName: 'Lesotho', dialString: '+269', flagIcon: '🇱🇸' },
  { commonName: 'Ukraine', dialString: '+380', flagIcon: '🇺🇦' },
  { commonName: 'Israel', dialString: '+972', flagIcon: '🇮🇱' },
  { commonName: 'Saudi Arabia', dialString: '+966', flagIcon: '🇸🇦' },
  { commonName: 'United Arab Emirates', dialString: '+971', flagIcon: '🇦🇪' },
].sort((a, b) => a.commonName.localeCompare(b.commonName));